name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: vimtor/action-zip@v1
        with:
          files: packs/ module.json
          dest: agwwz-content-module.zip
      
      - run: git config user.name wcrumb97
      - run: git config user.email wcrumb97@gmail.com
      - run: git add agwwz-content-module.zip
      - run: git commit -m "The files have been committed."
      - run: git push -f origin main
