name: Zip Files

on:
  push:
    branches: main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: vimtor/action-zip@v1
        with:
          files: packs/ module.json
          dest: agwwz-content-module.zip
         
      - uses: swinton/commit@v2.x
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         files: |
          agwwz-content-module.zip
         commit-message: Committing
         ref: refs/heads/my-branch
