name: Zip Files

on: workflow_dispatch

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: packs/ module.json
          dest: agwwz-content-module.zip
          
      - run: git config --global user.name "wcrumb97"
      - run: git config --global user.email "wcrumb97@gmail.com"
      - run: git add .
      - run: git commit -m "Update- Added the new content to the .zip file."

