name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: vimtor/action-zip@v1
        with:
          files: packs/ module.json
          dest: agwwz-content-module.zip
          
      - run: 
          git config --global user.name wcrumb97
          git config --global user.email wcrumb97@gmail.com
          git add agwwz-content-module.zip
          git commit -m "The files have been committed."
          git push -f origin main
