name: Zip Files

on: workflow_dispatch

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: packs/ module.json
          dest: agwwz-content-module.zip
          
  commit-to-main:
    runs-on: ubuntu-latest
    steps:
     - run: git config --local user.name "wcrumb97"
     - run: git config --local user.email "wcrumb97@gmail.com"
     - run: git add .
     - run: git status
