name: Zip Files

on: workflow_dispatch

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: zip -r agwwz-content-module.zip module.json packs/
          
      - run: git add agwwz-content-module.zip
      
      - run: git config --local user.email "wcrumb97@gmail.com"
      
      - run: git config --local user.name "wcrumb97"
      
      - run: git config --list 
